### ISSUE TITLE
Missing "-std=c++11" flag and "std::(f)abs" (mis)usage.

### ISSUE THREAD

**Issue by JacekHoleczek** [scarrazza/qcdloop#10]
The output from "`qcdloop-config --cppflags`" does NOT contain "`-std=c++11`", even though this flag is badly needed. Please fix it.

On this occasion, I would also like to ask you to improve the "qcdloop/maths.h" file a bit. Instead of:
`inline double  Abs(complex const& x)  { return std::fabs(x);}`
please use:
`inline double  Abs(complex const& x)  { return std::abs(x);}`

**Comment by scarrazza** [comment]
Thanks for pointing out this issue, I hope this is fixed in #12.

**Comment by JacekHoleczek** [comment]
Hi,
thanks.

I think maybe one should also use "std::abs" instead of "std::fabs" in:

inline double  Abs(double const& x)   { return std::fabs(x); }

I would also like to ask you to add a "fix" which I mentioned in another 
issue (badly needed on "CentOS" and related systems):

sed -i -e '{s#/usr/lib/gcc/x86_64-linux-gnu/\*#& 
/usr/lib/gcc/x86_64-redhat-linux/\*#}' CMakeLists.txt

It adds the "/usr/lib/gcc/x86_64-redhat-linux/*" entry to the "PATHS" in 
the "QUADMATH_LIBRARY" search (in "CMakeLists.txt").

Thanks ni advance,
Best regards,
Jacek.
