### ISSUE TITLE
Make patch release v2.0.10

### ISSUE THREAD

**Issue by matthewfeickert** [scarrazza/qcdloop#26]
@scarrazza now that you have 76fd63428ad4c00ac35db629eefde7da1e19673c in (which I haven't tested, but will assume also works for x86 macOS(?)) would you be willing to make a `v2.0.10` patch release?

Also, is 

https://github.com/scarrazza/qcdloop/blob/76fd63428ad4c00ac35db629eefde7da1e19673c/README.md#L48-L49

necessarily true anymore, as I thought that `clang` didn't support `quadmath`. Has that been fixed, or does this provide a workaround that doesn't require `quadmath`?

**Comment by scarrazza** [comment]
@matthewfeickert yes, I am planning to do so later today. Concerning `quadmath`, I believe nothing has really changed, we still have to use gcc for the compilation instead of clang.

**Comment by matthewfeickert** [comment]
> yes, I am planning to do so later today.

Fantastic! Thanks very much.

> Concerning `quadmath`, I believe nothing has really changed, we still have to use gcc for the compilation instead of clang.

Ah okay. Good to know.
