### ISSUE TITLE
Documentation website 404s

### ISSUE THREAD

**Issue by matthewfeickert** [scarrazza/qcdloop#27]
@scarrazza The current documentation website listed in the README

https://github.com/scarrazza/qcdloop/blob/76fd63428ad4c00ac35db629eefde7da1e19673c/README.md?plain=1#L9

and on the right hand side of the GitHub page currently 404s.

![image](https://github.com/user-attachments/assets/0f793c98-c3f0-430d-ab52-8818c0a87014)

Can this be updated or fixed?

**Comment by scarrazza** [comment]
Thanks, fixed.
