### ISSUE TITLE
Interest in being added as conda-forge feedstock maintainer? 

### ISSUE THREAD

**Issue by matthewfeickert** [scarrazza/qcdloop#30]
:wave: As part of a [larger community project](https://github.com/hep-packaging-coordination/packaging-hep-simulation-stack/issues/1) to try to do multi-platform packaging of the broader HEP simulation stack I've added QCDLoop to conda-forge: https://github.com/conda-forge/qcdloop-feedstock/.

Whenever I add something to conda-forge I like to also make sure that the project maintainers are aware of it and I also like to include them as feedstock maintainers so that they still have the ability to control the distribution of their project source code if they want to. This comes without any expectation of having to actually do the maintenance of the feedstock as it is unfair to expect additional work of project maintainers beyond the source code itself.

* @scarrazza Would you be interested in being listed as a conda-forge feedstock maintainer?

* Would you be open to a PR that would add conda-forge install instructions using `conda` and/or `pixi` to the README?

Note: As QCDLoop requires `quadmath`, at the moment I haven't gotten aarch64 Linux builds working (c.f. https://github.com/conda-forge/ctng-compilers-feedstock/issues/160) or macOS builds working on conda-forge, so currently only x86 and ppc64le Linux builds are supported from conda-forge. (I'm waiting to update to release `2.0.10+` till after I can solve some of these packaging issues.)

[![Conda Version](https://img.shields.io/conda/vn/conda-forge/qcdloop.svg)](https://anaconda.org/conda-forge/qcdloop) [![Conda Platforms](https://img.shields.io/conda/pn/conda-forge/qcdloop.svg)](https://anaconda.org/conda-forge/qcdloop)

I think that @scarrazza has a macOS machine from other GitHub Issues, but if you're on a Linux cluster somewhere you can already do

```console
# curl -fsSL https://pixi.sh/install.sh | bash  # Install pixi as my recommendation in general
# . ~/.bashrc
$ mkdir example && cd $_
$ pixi init
$ pixi add qcdloop
# pixi list  # will show you what's installed
# pixi run qcdloop-config --prefix  # runs anything after 'pixi run' inside of the environment created
# pixi shell # is like activating a conda-environment
```

<details>
<summary>Docker example:</summary>

```console
$ docker run --rm -ti fedora:42 
[root@6c56685f897c /]# curl -fsSL https://pixi.sh/install.sh | bash
This script will automatically download and install Pixi (latest) for you.
Getting it from this url: https://github.com/prefix-dev/pixi/releases/latest/download/pixi-x86_64-unknown-linux-musl.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 14.8M  100 14.8M    0     0  4663k      0  0:00:03  0:00:03 --:--:-- 6486k
The 'pixi' binary is installed into '/root/.pixi/bin'
Updating '/root/.bashrc'
Please restart or source your shell.
[root@6c56685f897c /]# . /root/.bashrc 
[root@6c56685f897c /]# mkdir example && cd $_
[root@6c56685f897c example]# pixi init
✔ Created /example/pixi.toml
[root@6c56685f897c example]# pixi add qcdloop
✔ Added qcdloop >=2.0.9,<3
[root@6c56685f897c example]# pixi list
Package        Version  Build        Size       Kind   Source
_libgcc_mutex  0.1      conda_forge  2.5 KiB    conda  _libgcc_mutex-0.1-conda_forge.tar.bz2
_openmp_mutex  4.5      2_gnu        23.1 KiB   conda  _openmp_mutex-4.5-2_gnu.tar.bz2
bzip2          1.0.8    h4bc722e_7   246.9 KiB  conda  bzip2-1.0.8-h4bc722e_7.conda
grep           3.11     h7af0fdc_3   282.5 KiB  conda  grep-3.11-h7af0fdc_3.conda
libgcc         14.2.0   h77fa898_1   828.9 KiB  conda  libgcc-14.2.0-h77fa898_1.conda
libgcc-ng      14.2.0   h69a702a_1   52.9 KiB   conda  libgcc-ng-14.2.0-h69a702a_1.conda
libgfortran    14.2.0   h69a702a_1   52.7 KiB   conda  libgfortran-14.2.0-h69a702a_1.conda
libgfortran5   14.2.0   hd5240d6_1   1.4 MiB    conda  libgfortran5-14.2.0-hd5240d6_1.conda
libgomp        14.2.0   h77fa898_1   450.2 KiB  conda  libgomp-14.2.0-h77fa898_1.conda
libstdcxx      14.2.0   hc0a3c3a_1   3.7 MiB    conda  libstdcxx-14.2.0-hc0a3c3a_1.conda
libzlib        1.3.1    hb9d3cd8_2   59.5 KiB   conda  libzlib-1.3.1-hb9d3cd8_2.conda
pcre2          10.44    hba22ea6_2   930 KiB    conda  pcre2-10.44-hba22ea6_2.conda
qcdloop        2.0.9    h024ca30_1   1 MiB      conda  qcdloop-2.0.9-h024ca30_1.conda
[root@6c56685f897c example]# pixi run qcdloop-config --prefix
/example/.pixi/envs/default
[root@6c56685f897c example]# pixi shell
(example) [root@6c56685f897c example]# qcdloop-config --prefix
/example/.pixi/envs/default
(example) [root@6c56685f897c example]# find $CONDA_PREFIX -type f -iname "libqcdloop.so"
/example/.pixi/envs/default/lib/libqcdloop.so
(example) [root@6c56685f897c example]# exit
logout
[root@6c56685f897c example]#
```

</details>

**Comment by scarrazza** [comment]
@matthewfeickert thanks for the proposal. Yes, please go ahead with both points.
