### ISSUE TITLE
qcdloop-config --version broken

### ISSUE THREAD

**Issue by a-maier** [scarrazza/qcdloop#7]
Hi,

since the switch to cmake (commit 2445ffda352)

`qcdloop-config --version`

prints an empty line.

**Comment by scarrazza** [comment]
Thanks for reporting this issue, should be fixed in https://github.com/scarrazza/qcdloop/commit/75447500f486cf43c7f9d62382567b44d25dc1d8.

**Comment by a-maier** [comment]
Thanks. Works now.
